export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_BY_CATEGORY = 'GET_PRODUCTS_BY_CATEGORY';
export const GET_PRODUCTS_BY_ID = 'GET_PRODUCTS_BY_ID';

export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_ROOT = 'GET_CATEGORY_ROOT';
